# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PseudoStockArchiveApp', '0003_auto_20180107_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='marketCap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tradingdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 7, 12, 24, 46, 738803, tzinfo=utc)),
        ),
    ]
