# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 06:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PseudoStockArchiveApp', '0005_auto_20180107_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 11, 6, 29, 9, 897160, tzinfo=utc)),
        ),
    ]
