# Generated by Django 2.0.1 on 2018-01-19 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PseudoStockArchiveApp', '0006_auto_20180111_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 9, 4, 15, 348739, tzinfo=utc)),
        ),
    ]
