# Generated by Django 2.0.1 on 2018-01-19 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PseudoStockArchiveApp', '0009_auto_20180119_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 19, 10, 34, 56, 102803, tzinfo=utc)),
        ),
    ]
