# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 10:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('PseudoStockArchiveApp', '0009_auto_20180119_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 10, 50, 9, 666101, tzinfo=utc)),
        ),
    ]
